global:
  name: SBOM SPDX Landscape
  short_name: SBOM
  repo: spdx/sbom-landscape
  website: https://landscape.spdx.dev
  short_domain: l.spdx.dev
  company_url: https://spdx.dev
  email: info@spdx.dev
  self: https://www.crunchbase.com/organization/software-package-data-exchange
  slack_channel: T08PSQ7BQ/BM7M5TKSR/Xjll8jWb2cgpO7aOCGxUtebU
  membership: SBOM SPDX Adopter
  meta:
    title: SBOM SPDX Landscape
    fb_admin: alex.contini.94
    description: Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets
    twitter: '@spdxteam'
    google_site_verification: u_xqWIf8_EzRP4UF92px16rTSoIP49D_g9i7M-4rXds
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  flags:
    hide_license_for_categories:
      - SBOM SPDX Adopter
twitter:
  search: landscape.spdx.dev
  url: https://landscape.spdx.dev
  text: SBOM SPDX Landscape
relation:
  label: SBOM SPDX Relation
  url: todo
  values:
    - id: member
      label: SBOM SPDX Adopters
      tag: TODO Group Member
      children: []
    - id: false
      label: Change me
      url: 'no'
membership:
  General:
    name: SBOM SPDX
    label: Adopter
    funding: General
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
    crunchbase_and_children: https://www.crunchbase.com/organization/linux-foundation
  'false':
    funding: 'No'
home:
  header: >
    <h1>SBOM SPDX Landscape</h1> The SBOM SPDX landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank" href="images/landscape.pdf">pdf</a>)
    is dynamically generated below. It is modeled after the <a href="http://landscape.cncf.io">CNCF landscape</a> and based on the same open source code.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
ads:
  - url: https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/?utm_source=ospo_landscape&utm_medium=web&utm_campaign=kccnceu20
    image: /images/info1.jpg
    title: Kubecon + CloudNativeCon Europe 2020
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /license=apache-license-2-0
    label: Apache-2.0 landscape
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: SBOM SPDX Landscape
    fullscreen_header: See the interactive landscape at l.spdx.dev
    elements:
      - type: HorizontalCategory
        category: SBOM SPDX Adopter
        width: 735
        height: 320
        top: 0
        left: 0
        color: rgb(126,115,14)
        fit_width: true
      - type: Vertical Category
        category: SBOM SPDX Tools
        width: 220
        height: 300
        top: 20
        left: 755
        color: rgb(103,66,18)
        fit_width: true
      - type: LandscapeInfo
        width: 310
        height: 200
        top: 330
        left: 665
        children:
          - type: text
            text: |
              This landscape is intended as a map to explore the SBOM SPDX community.
            top: 65
            width: 160
            right: 20
            font_size: 12
          - type: image
            image: qr.svg
            top: 25
            left: 20
            width: 90
            height: 90
            title: QR Code
          - type: title
            title: l.spdx.dev
            top: 120
            left: 10
            font_size: 16
          - type: image
            image: left-logo.svg
            width: 80
            right: 105
            top: 10
            title: Landscape Logo
          - type: image
            image: right-logo.svg
            width: 80
            right: 20
            top: 15
            title: SPDX Logo
test:
  header: SBOM SPDX Landscape
  section: SBOM SPDX Adopters
  logo: adobe-adopter.svg
